# Generated by Django 5.0.6 on 2024-06-18 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0003_customer_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('tagline', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=80)),
                ('body_text', models.TextField()),
                ('pub_date', models.DateField()),
                ('number_of_comments', models.IntegerField()),
                ('rating', models.FloatField()),
                ('author', models.ManyToManyField(to='orm_app.author')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm_app.blog')),
            ],
        ),
    ]
