# Generated by Django 5.0.6 on 2024-06-17 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('features', models.TextField(help_text='features of the mobile')),
                ('and_version', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=3.4)),
                ('launched', models.DateField(auto_now=True)),
                ('offer', models.BooleanField(default=False)),
                ('org_email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('mob_images', models.FileField(upload_to='mobile_images')),
                ('price', models.BigIntegerField(default=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_desc', models.TextField()),
                ('mobile', models.ManyToManyField(to='model_fields.mobile')),
            ],
        ),
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('mobile_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='model_fields.mobile')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_fields.mobile')),
            ],
        ),
    ]
